name: BerlinCoach
options:
  bundleIdPrefix: com.tatsuya
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    DEVELOPMENT_TEAM: ""
    PRODUCT_BUNDLE_IDENTIFIER: com.tatsuya.berlincoach
targets:
  BerlinCoach:
    type: application
    platform: iOS
    sources:
      - path: BerlinCoach
    resources:
      - path: BerlinCoach/Assets.xcassets
    info:
      path: BerlinCoach/Info.plist
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: BerlinCoach/Info.plist
